/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Login200,
  Signup201,
  VerifySession200
} from '../models';


export const getSignupResponseMock = (overrideResponse: Partial<Extract<Signup201, object>> = {}): Signup201 => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getLoginResponseMock = (overrideResponse: Partial<Extract<Login200, object>> = {}): Login200 => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getVerifySessionResponseMock = (overrideResponse: Partial<Extract<VerifySession200, object>> = {}): VerifySession200 => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getSignupMockHandler = (overrideResponse?: Signup201 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Signup201> | Signup201), options?: RequestHandlerOptions) => {
  return http.post('*/auth/signup', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSignupResponseMock(),
      { status: 201
      })
  }, options)
}

export const getLoginMockHandler = (overrideResponse?: Login200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Login200> | Login200), options?: RequestHandlerOptions) => {
  return http.post('*/auth/login', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginResponseMock(),
      { status: 200
      })
  }, options)
}

export const getVerifySessionMockHandler = (overrideResponse?: VerifySession200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<VerifySession200> | VerifySession200), options?: RequestHandlerOptions) => {
  return http.get('*/auth/verify-session', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getVerifySessionResponseMock(),
      { status: 200
      })
  }, options)
}
export const getAuthMock = () => [
  getSignupMockHandler(),
  getLoginMockHandler(),
  getVerifySessionMockHandler()
]
