/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Login200,
  Login422,
  Login500,
  LoginBody,
  Signup201,
  Signup409,
  Signup422,
  Signup500,
  SignupBody,
  VerifySession200,
  VerifySession401,
  VerifySession500
} from '../models';





/**
 * @summary Signup an user
 */
export type signupResponse201 = {
  data: Signup201
  status: 201
}

export type signupResponse409 = {
  data: Signup409
  status: 409
}

export type signupResponse422 = {
  data: Signup422
  status: 422
}

export type signupResponse500 = {
  data: Signup500
  status: 500
}

export type signupResponseSuccess = (signupResponse201) & {
  headers: Headers;
};
export type signupResponseError = (signupResponse409 | signupResponse422 | signupResponse500) & {
  headers: Headers;
};

export type signupResponse = (signupResponseSuccess | signupResponseError)

export const getSignupUrl = () => {




  return `http://localhost:8010/proxy/auth/signup`
}

export const signup = async (signupBody: SignupBody, options?: RequestInit): Promise<signupResponse> => {

  const res = await fetch(getSignupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signupBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: signupResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as signupResponse
}




export const getSignupMutationOptions = <TError = Signup409 | Signup422 | Signup500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignupBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignupBody}, TContext> => {

const mutationKey = ['signup'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signup>>, {data: SignupBody}> = (props) => {
          const {data} = props ?? {};

          return  signup(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SignupMutationResult = NonNullable<Awaited<ReturnType<typeof signup>>>
    export type SignupMutationBody = SignupBody
    export type SignupMutationError = Signup409 | Signup422 | Signup500

    /**
 * @summary Signup an user
 */
export const useSignup = <TError = Signup409 | Signup422 | Signup500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignupBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signup>>,
        TError,
        {data: SignupBody},
        TContext
      > => {
      return useMutation(getSignupMutationOptions(options), queryClient);
    }
    /**
 * @summary Login an user
 */
export type loginResponse200 = {
  data: Login200
  status: 200
}

export type loginResponse422 = {
  data: Login422
  status: 422
}

export type loginResponse500 = {
  data: Login500
  status: 500
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse422 | loginResponse500) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {




  return `http://localhost:8010/proxy/auth/login`
}

export const login = async (loginBody: LoginBody, options?: RequestInit): Promise<loginResponse> => {

  const res = await fetch(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponse
}




export const getLoginMutationOptions = <TError = Login422 | Login500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginBody}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginBody}> = (props) => {
          const {data} = props ?? {};

          return  login(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginBody
    export type LoginMutationError = Login422 | Login500

    /**
 * @summary Login an user
 */
export const useLogin = <TError = Login422 | Login500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginBody},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }
    /**
 * @summary Verify is user session is valid
 */
export type verifySessionResponse200 = {
  data: VerifySession200
  status: 200
}

export type verifySessionResponse401 = {
  data: VerifySession401
  status: 401
}

export type verifySessionResponse500 = {
  data: VerifySession500
  status: 500
}

export type verifySessionResponseSuccess = (verifySessionResponse200) & {
  headers: Headers;
};
export type verifySessionResponseError = (verifySessionResponse401 | verifySessionResponse500) & {
  headers: Headers;
};

export type verifySessionResponse = (verifySessionResponseSuccess | verifySessionResponseError)

export const getVerifySessionUrl = () => {




  return `http://localhost:8010/proxy/auth/verify-session`
}

export const verifySession = async ( options?: RequestInit): Promise<verifySessionResponse> => {

  const res = await fetch(getVerifySessionUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: verifySessionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as verifySessionResponse
}





export const getVerifySessionQueryKey = () => {
    return [
    `http://localhost:8010/proxy/auth/verify-session`
    ] as const;
    }


export const getVerifySessionQueryOptions = <TData = Awaited<ReturnType<typeof verifySession>>, TError = VerifySession401 | VerifySession500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifySession>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVerifySessionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof verifySession>>> = ({ signal }) => verifySession({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof verifySession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VerifySessionQueryResult = NonNullable<Awaited<ReturnType<typeof verifySession>>>
export type VerifySessionQueryError = VerifySession401 | VerifySession500


export function useVerifySession<TData = Awaited<ReturnType<typeof verifySession>>, TError = VerifySession401 | VerifySession500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifySession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifySession>>,
          TError,
          Awaited<ReturnType<typeof verifySession>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerifySession<TData = Awaited<ReturnType<typeof verifySession>>, TError = VerifySession401 | VerifySession500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifySession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifySession>>,
          TError,
          Awaited<ReturnType<typeof verifySession>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerifySession<TData = Awaited<ReturnType<typeof verifySession>>, TError = VerifySession401 | VerifySession500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifySession>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Verify is user session is valid
 */

export function useVerifySession<TData = Awaited<ReturnType<typeof verifySession>>, TError = VerifySession401 | VerifySession500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifySession>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVerifySessionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




