/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
export type SignupBody = {
  username: string;
  password: string;
};

export type Signup201 = {
  message: string;
};

export type Signup409 = {
  message: string;
};

export type LoginBody = {
  username: Username;
  password: Password;
};

export type Login200 = {
  message: string;
};

export type VerifySession200 = {
  message: string;
};

