/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
export type SignupBody = {
  username: string;
  email: string;
  password: string;
};

export type Signup201 = {
  message: string;
};

export type Signup409 = {
  message: string;
};

export type LoginBody = {
  username: Username;
  password: Password;
};

export type Login200 = {
  message: string;
};

export type VerifySession200 = {
  message: string;
};

export type CreatePostBody = {
  content: string;
};

export type CreatePost201 = {
  message: string;
};

export type UpdatePostBody = {
  content: Content;
};

export type GetFeed200 = {
  message: string;
  /** @maxItems 10 */
  data: Data[];
};

export type GetFeedPagination200 = {
  message: string;
  data: Data;
};

export type GetPost200DataAuthor = {
  username?: string;
};

export type GetPost200Data = {
  id?: string;
  content?: string;
  publishedAt?: string;
  updatedAt?: string | unknown;
  author?: GetPost200DataAuthor;
};

export type GetPost200 = {
  message: string;
  data: GetPost200Data;
};

export type GetAllPosts200 = {
  message: string;
  data: Data;
};

export type GetAllPostsPagination200 = {
  message: string;
  data: Data;
};

