/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAllPosts200DataItemAuthor } from './getAllPosts200DataItemAuthor';

export type GetAllPosts200DataItem = {
  id: string;
  content: string;
  publishedAt: string;
  updatedAt: string | null;
  author: GetAllPosts200DataItemAuthor;
};
