/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAllPostsPagination200DataItem } from './getAllPostsPagination200DataItem';

export type GetAllPostsPagination200 = {
  message: string;
  /** @maxItems 10 */
  data: GetAllPostsPagination200DataItem[];
};
