/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAllPosts200DataItem } from './getAllPosts200DataItem';

export type GetAllPosts200 = {
  message: string;
  /** @maxItems 10 */
  data: GetAllPosts200DataItem[];
};
