/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAllPostsPagination200DataItemAuthor } from './getAllPostsPagination200DataItemAuthor';

export type GetAllPostsPagination200DataItem = {
  id: string;
  content: string;
  publishedAt: string;
  updatedAt: string | null;
  author: GetAllPostsPagination200DataItemAuthor;
};
