/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFeed200DataItem } from './getFeed200DataItem';

export type GetFeed200 = {
  message: string;
  /** @maxItems 10 */
  data: GetFeed200DataItem[];
};
