/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFeedPagination200DataItemAuthor } from './getFeedPagination200DataItemAuthor';

export type GetFeedPagination200DataItem = {
  id: string;
  content: string;
  publishedAt: string;
  updatedAt: string | null;
  author: GetFeedPagination200DataItemAuthor;
};
