/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFeedPagination200DataItem } from './getFeedPagination200DataItem';

export type GetFeedPagination200 = {
  message: string;
  /** @maxItems 10 */
  data: GetFeedPagination200DataItem[];
};
