/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFeed200DataItemAuthor } from './getFeed200DataItemAuthor';

export type GetFeed200DataItem = {
  id: string;
  content: string;
  publishedAt: string;
  updatedAt: string | null;
  author: GetFeed200DataItemAuthor;
};
