/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPost200Data } from './getPost200Data';

export type GetPost200 = {
  message: string;
  data: GetPost200Data;
};
