/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * odinbook API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPost200DataAuthor } from './getPost200DataAuthor';

export type GetPost200Data = {
  id: string;
  content: string;
  publishedAt: string;
  updatedAt: string | null;
  author: GetPost200DataAuthor;
};
